// Generated by Wrangler by running `wrangler types`
// Manual Phase 1 additions are present because Wrangler 3.114.17 warns on
// the current ai_search binding and does not emit secret-only env fields.

interface Env {
	KB: {
		search(options: {
			messages: Array<{ role: string; content: string }>;
			ai_search_options?: Record<string, unknown>;
		}): Promise<unknown>;
	};
	CF_ACCOUNT_ID: string;
	AI_GATEWAY_ID: string;
	MODEL_PROVIDER: "workersai" | "azureopenai" | string;
	WORKERS_AI_MODEL: string;
	AZURE_RESOURCE_NAME: string;
	AZURE_DEPLOYMENT_NAME: string;
	AZURE_API_VERSION: string;
	ALLOWED_ORIGIN: string;
	PHOENIX_DEBUG_ENABLED: string;
	CF_API_TOKEN?: string;
	PHOENIX_DEBUG_TOKEN?: string;
	AZURE_OPENAI_API_KEY?: string;
}
